# -*- coding: utf-8 -*-
"""data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10O0jquDYq83wHOo1u5gJFzYzZeG9sy6r
"""

import pandas as pd
import numpy as np
raw_data = {
    'Patient_ID': [101, 102, 103, 104, 105, 106],
    'Age': [25, 34, np.nan, 45, 29, 52],
    'Weight': [70, 85, 65, "72kg", 95, 60],
    'Malaria_Test': ['Positive', 'Negative', 'Negative', 'Positive', 'Positive', 'Negative']
}
df_temp = pd.DataFrame(raw_data)
df_temp.to_csv('clinic_raw_data.csv', index=False)
print("File 'clinic_raw_data.csv' had been created!")
df = pd.read_csv('clinic_raw_data.csv')
print("---Raw Data---")
print(df.head())
print("\n--- Data Info ---")
print(df.info())
df["Weight"] = df["Weight"].astype(str).str.replace('kg', '')
df['Weight'] = pd.to_numeric(df['Weight'])
avg_age = df['Age'].mean()
df['Age'] = df['Age'].fillna(avg_age)
print("--- Cleaned Data ---")
print(df)
summary = df.groupby('Malaria_Test').agg({'Age': 'mean', 'Weight': 'mean'})
print("--- Summary ---")
print(summary)